### ISSUE TITLE
new GraphQL typeDefs and resolvers defined

### ISSUE THREAD

**Issue by socialcancer** [katcontrerasdev/uclaFinalProject#18]

**Comment by socialcancer** [comment]
Had some road-blocks with configuring the typedefs and the models. Kat also looked into this issue.

**Comment by katcontrerasdev** [comment]
Marissa and Kat resolved typedefs and models through a few remote sessions. See attached successful query from insomnia. 
<img width="2161" alt="Screen Shot 2022-04-03 at 8 30 01 PM" src="https://user-images.githubusercontent.com/90402597/161469271-915708bb-60b0-486e-9359-4f7c7c1eac00.png">
