### ISSUE TITLE
Presentation Deck

### ISSUE THREAD

**Issue by katcontrerasdev** [katcontrerasdev/uclaFinalProject#22]
Presentation Deck

**Comment by mbelom** [comment]
Completed with Google Slides and ready for class presentation. 
-Created and wrote up the presentation 
  -Message and elevator pitched created 
  -User's story
  -Theme design w/ free adobe pictures created
  -Processes used are noted 
  -Issues during project placed
  -Mobile design was created and placed in 
  -Overall layout and project goals and design created 
  
[WHATS-GOOD APP.pdf](https://github.com/katcontrerasdev/uclaFinalProject/files/8406577/WHATS-GOOD.APP.pdf)
